import MicroLEDModel from "./microled_model.jsx";
import React, { useState, useEffect, useRef } from "react";
import '../../styles/s04g7/microled.css';
import '../../styles/s04g7/pagebg.css';
import '../../styles/s04g7/era.css';
import evolutionImg from "../../assets/s04g7/microled-evolution-structure.webp";
import jiangImg from "../../assets/s04g7/prof-hongxing-jiang.webp";
import linImg from "../../assets/s04g7/prof-jingyu-lin.webp";

{/*
    MicroLED Parts Information:
    label: Name of MicroLED Part
    description: MicroLED Part Description
    processMicroledTitle: Name of the Process Associated with the Part
    processMicroledDescription: Description of the Associated Process
*/}
const PARTS = [
    {
        id: "backplane",
        label: "TFT Backplane",
        description:
            "A thin-film transistor array that drives current to each micro-LED chip individually, controlling how bright every sub-pixel glows.",
        processMicroledTitle: "Driving the Chips",
        processMicroledDescription:
            "Each transistor in the backplane acts as a switch, delivering a precise amount of current to the chip sitting above it. Varying that current changes how much light the chip emits, which is how each sub-pixel's brightness is controlled independently.",
    },
    {
        id: "chips",
        label: "Micro-LED Chips",
        description:
            "Thousands of microscopic self-emitting diodes. Each pixel is built from a red, green, and blue chip that light up independently, without needing a backlight.",
        processMicroledTitle: "Light Emission",
        processMicroledDescription:
            "When current reaches a chip, electrons and holes recombine inside its semiconductor material and release energy as light. Because red, green, and blue chips can each be driven to a different brightness, combining their output produces every color the pixel displays.",
    },
    {
        id: "electrode",
        label: "Electrode",
        description:
            "A shared, transparent conductive layer above the chip array that completes the circuit, carrying current out of each chip's top contact.",
        processMicroledTitle: "Completing the Circuit",
        processMicroledDescription:
            "Current flows from the backplane up into the bottom of each chip, then out through its top contact into this shared electrode layer above it. This gives every chip a return path without needing a separate wire for each one.",
    },
    {
        id: "cover",
        label: "Cover Glass",
        description:
            "A protective transparent layer sealing the panel and letting the light emitted below pass through to the viewer.",
        processMicroledTitle: "Light Transmission",
        processMicroledDescription:
            "Light generated by the chips travels upward through the electrode and exits through the cover glass. This final layer protects the delicate chip array underneath while staying optically clear enough not to distort or dim the image.",
    },
];

const TABS = [
    { id: "model", label: "Model" },
    { id: "evolution", label: "Evolution" },
    { id: "tech", label: "Technical Description" },
    { id: "apps", label: "Applications" },
    { id: "perf", label: "Performance Evaluation" },
    { id: "quiz", label: "Quiz Challenge" },
    { id: "refs", label: "References" }
];

const QUESTION_POOL = [
    {
        question: "In what year was MicroLED technology invented?",
        options: ["1994", "2000", "2012", "2018"],
        correct: 1
    },
    {
        question: "MicroLED technology was originally developed by researchers at which university?",
        options: ["MIT", "Stanford University", "Texas Tech University", "Seoul National University"],
        correct: 2
    },
    {
        question: "Which company launched the first commercial MicroLED-based display, the 55-inch \"Crystal LED,\" in 2012?",
        options: ["Samsung", "Sony", "LG", "Apple"],
        correct: 1
    },
    {
        question: "What did Samsung call its 146-inch MicroLED display unveiled at CES 2018?",
        options: ["The Wall", "Crystal LED", "QLED Prime", "MicroVision"],
        correct: 0
    },
    {
        question: "What currently limits MicroLED to premium televisions, wearables, and AR devices?",
        options: ["Manufacturing complexity and cost", "Poor contrast performance", "Limited color gamut", "Slow response time"],
        correct: 0
    },
    {
        question: "Which layer houses the circuitry that drives current to each micro-LED chip individually?",
        options: ["Cover Glass", "Common Electrode", "TFT Backplane", "Phosphor Coating"],
        correct: 2
    },
    {
        question: "What happens inside a chip's semiconductor layers to produce light?",
        options: [
            "Liquid crystals twist to block or pass light",
            "Electrons and holes recombine and release energy as light",
            "Gas ionizes into plasma and emits ultraviolet photons",
            "A backlight shines through a color filter"
        ],
        correct: 1
    },
    {
        question: "What is the role of the common electrode in a MicroLED display?",
        options: [
            "It seals the panel from moisture and dust",
            "It stores the image data for each frame",
            "It completes the circuit by carrying current out of each chip's top contact",
            "It converts ultraviolet light into visible color"
        ],
        correct: 2
    },
    {
        question: "What is the purpose of the cover glass in a MicroLED panel?",
        options: [
            "It drives current to each chip",
            "It protects the chip array while letting emitted light pass through",
            "It generates the red, green, and blue light",
            "It completes the electrical circuit"
        ],
        correct: 1
    },
    {
        question: "True or False: A MicroLED display needs a backlight unit to produce an image.",
        options: ["True", "False"],
        correct: 1
    },
    {
        question: "What is one of the biggest manufacturing challenges facing MicroLED today?",
        options: [
            "Mass transfer of millions of microscopic LEDs with high precision",
            "A shortage of glass substrates",
            "Excessive screen burn-in",
            "Inability to display color"
        ],
        correct: 0
    },
    {
        question: "True or False: Because each pixel is its own emitter, MicroLED displays are not prone to burn-in.",
        options: ["True", "False"],
        correct: 0
    },
];

const playSound = (soundType) => {
    try {
        const audioContext = new (window.AudioContext || window.webkitAudioContext)();
        const oscillator = audioContext.createOscillator();
        const volume = audioContext.createGain();

        oscillator.connect(volume);
        volume.connect(audioContext.destination);

        if (soundType === "correct") {
            oscillator.type = "sine";
            oscillator.frequency.setValueAtTime(523.25, audioContext.currentTime);
            oscillator.frequency.setValueAtTime(659.25, audioContext.currentTime + 0.1);
            oscillator.frequency.setValueAtTime(783.99, audioContext.currentTime + 0.2);

            volume.gain.setValueAtTime(0.5, audioContext.currentTime);
            volume.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.4);

            oscillator.start(audioContext.currentTime);
            oscillator.stop(audioContext.currentTime + 0.4);

        } else if (soundType === "wrong") {
            oscillator.type = "triangle";
            oscillator.frequency.setValueAtTime(311.13, audioContext.currentTime);
            oscillator.frequency.setValueAtTime(220, audioContext.currentTime + 0.15);

            volume.gain.setValueAtTime(0.45, audioContext.currentTime);
            volume.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.3);

            oscillator.start(audioContext.currentTime);
            oscillator.stop(audioContext.currentTime + 0.3);

        } else if (soundType === "complete") {
            const melody = [523.25, 587.33, 659.25, 783.99, 1046.5];

            melody.forEach((note, index) => {
                const noteOsc = audioContext.createOscillator();
                const noteVolume = audioContext.createGain();

                noteOsc.connect(noteVolume);
                noteVolume.connect(audioContext.destination);

                noteOsc.type = "sine";
                noteOsc.frequency.value = note;

                noteVolume.gain.setValueAtTime(0.4, audioContext.currentTime + index * 0.12);
                noteVolume.gain.exponentialRampToValueAtTime(
                    0.01,
                    audioContext.currentTime + index * 0.12 + 0.5
                );

                noteOsc.start(audioContext.currentTime + index * 0.12);
                noteOsc.stop(audioContext.currentTime + index * 0.12 + 0.5);
            });
        }
    } catch (err) {
    }
};

const getRandomQuestions = (count) => {
    const shuffled = [...QUESTION_POOL].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
};

export default function MicroLEDViewer() {
    const [activeTab, setActiveTab] = useState('model');
    const [hoveredIdx, setHoveredIdx] = useState(null);             // for the hover effect in the menu tab
    const [selectedPart, setSelectedPart] = useState('backplane');
    const [animate, setAnimate] = useState(false);
    const activeBtn = (current, target) => `btn ${current === target ? 'active' : ''}`;
    const activeInfo = PARTS.find((p) => p.id === selectedPart) || PARTS[0];

    const [currentQuestion, setCurrentQuestion] = useState(0);
    const [selectedAnswer, setSelectedAnswer] = useState(null);
    const [score, setScore] = useState(0);
    const [quizComplete, setQuizComplete] = useState(false);
    const [quizQuestions, setQuizQuestions] = useState([]);
    const canvasRef = useRef(null);
    const particlesRef = useRef([]);
    const animFrameRef = useRef(null);

    useEffect(() => {
        if (activeTab === 'quiz') {
            setQuizQuestions(getRandomQuestions(5));
        }
    }, [activeTab]);

    const handleAnswer = (index) => {
        setSelectedAnswer(index);
        const isCorrect = index === quizQuestions[currentQuestion].correct;
        playSound(isCorrect ? 'correct' : 'wrong');
        if (isCorrect) setScore(prev => prev + 1);

        setTimeout(() => {
            if (currentQuestion < quizQuestions.length - 1) {
                setCurrentQuestion(prev => prev + 1);
                setSelectedAnswer(null);
            } else {
                setQuizComplete(true);
                playSound('complete');
            }
        }, 1200);
    };

    const resetQuiz = () => {
        setCurrentQuestion(0);
        setSelectedAnswer(null);
        setScore(0);
        setQuizComplete(false);
        setQuizQuestions(getRandomQuestions(5));
        particlesRef.current = [];
        if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
    };

    useEffect(() => {
        if (!quizComplete || score !== quizQuestions.length || !canvasRef.current) return;

        const canvas = canvasRef.current;
        const ctx = canvas.getContext('2d');
        const colors = ['#0f6e56', '#E24B4A', '#639922', '#378ADD', '#cfe9fb', '#5076a7'];

        const resizeCanvas = () => {
            canvas.width = canvas.offsetWidth;
            canvas.height = canvas.offsetHeight;
        };
        resizeCanvas();
        window.addEventListener('resize', resizeCanvas);

        for (let i = 0; i < 180; i++) {
            particlesRef.current.push({
                x: Math.random() * canvas.width,
                y: Math.random() * -canvas.height,
                size: Math.random() * 8 + 4,
                color: colors[Math.floor(Math.random() * colors.length)],
                speedX: (Math.random() - 0.5) * 4,
                speedY: Math.random() * 3 + 2,
                rotation: Math.random() * 360,
                rotationSpeed: (Math.random() - 0.5) * 8
            });
        }

        const animate = () => {
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            particlesRef.current = particlesRef.current.filter(p => p.y < canvas.height + 20);

            particlesRef.current.forEach(p => {
                p.x += p.speedX;
                p.y += p.speedY;
                p.rotation += p.rotationSpeed;

                ctx.save();
                ctx.translate(p.x, p.y);
                ctx.rotate((p.rotation * Math.PI) / 180);

                ctx.fillStyle = p.color;
                ctx.fillRect(-p.size / 2, -p.size / 2, p.size, p.size);
                ctx.restore();
            });

            if (particlesRef.current.length > 0) {
                animFrameRef.current = requestAnimationFrame(animate);
            }
        };
        animate();

        return () => {
            window.removeEventListener('resize', resizeCanvas);
            if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
        };
    }, [quizComplete, score, quizQuestions.length]);

    return (
        <div className="microled-page">
            <div className="bg"></div>

            <div className="microled-nav-header">
                <div className="back-button-container">
                    <a href="/s04g7" className="link-pill lower">
                        ← Go Back
                    </a>
                </div>

                <div
                    className="tabs-wrap"
                    style={{
                        '--active-index': TABS.findIndex(t => t.id === activeTab),
                        '--hover-index': hoveredIdx !== null ? hoveredIdx : TABS.findIndex(t => t.id === activeTab),
                        '--is-hovered': hoveredIdx !== null ? 1 : 0
                    }}
                >
                    <div className="tab-slidebar" />
                    <div className="tab-bar" />

                    {TABS.map((tab, idx) => (
                        <button
                            key={tab.id}
                            className={`tab-label ${activeTab === tab.id ? 'active' : ''}`}
                            onClick={() => setActiveTab(tab.id)}
                            onMouseEnter={() => setHoveredIdx(idx)}
                            onMouseLeave={() => setHoveredIdx(null)}
                        >
                            <span>{tab.label}</span>
                        </button>
                    ))}
                </div>
            </div>

            {activeTab === 'model' ? (
                <>
                    <div className="microled-top-side">
                        <h2 className="microled-info__title">General Process</h2>
                        <p className="microled-info__desc">
                            A MicroLED display is built on a TFT backplane wired with its own miniature
                            switch for every red, green, and blue chip. When current is delivered to a chip,
                            electrons and holes recombine inside its semiconductor layers and release the
                            energy as light directly, with no backlight involved. That light exits through a
                            shared common electrode and finally through a protective cover glass to reach the
                            viewer. Because every chip is its own light source and can be dimmed or switched
                            off individually, MicroLED panels are capable of true black levels and precise,
                            pixel-level control, much like other self-emissive display technologies.
                        </p>
                    </div>

                    <div className="microled-split-layout">
                        <div className="microled-info-side">
                            <h2 className="microled-info__title">{activeInfo.label}</h2>
                            <p className="microled-info__desc">{activeInfo.description}
                            </p>

                            <div className="microled-dynamic-box" style={{ marginTop: '2rem' }}>
                                <h3 className="microled-info__title">{activeInfo.processMicroledTitle}</h3>
                                <p className="microled-info__desc">
                                    {activeInfo.processMicroledDescription}
                                </p>
                            </div>
                        </div>

                        <div className="microled-model-side">
                            <p className="microled-info__desc">
                                💡 Select a part or animate the light emission below!
                                <br></br>
                                Check the model to know more about the different layers!
                            </p>

                            <div className="controls">
                                <span>Parts:</span>
                                <button className={activeBtn(selectedPart, 'backplane')} onClick={() => setSelectedPart('backplane')}>Backplane</button>
                                <button className={activeBtn(selectedPart, 'electrode')} onClick={() => setSelectedPart('electrode')}>Electrode</button>
                                <button className={activeBtn(selectedPart, 'chips')} onClick={() => setSelectedPart('chips')}>Chips</button>
                                <button className={activeBtn(selectedPart, 'cover')} onClick={() => setSelectedPart('cover')}>Cover</button>
                            </div>

                            <div className="controls">
                                <button
                                    className={`btn-animate-light ${animate ? 'active-glow' : ''}`}
                                    onClick={() => setAnimate(!animate)}
                                >
                                    {animate ? 'Stop Light' : 'Click To Animate Light'}
                                </button>
                            </div>

                            <MicroLEDModel selectedPart={selectedPart} setSelectedPart={setSelectedPart} animate={animate} />
                        </div>
                    </div>
                </>
            ) : (
                <div className="microled-top-side">
                    {activeTab === 'evolution' && (
                        <>
                            <h2 className="microled-info__title">Evolution</h2>
                            <img
                                src={evolutionImg.src}
                                alt="Microled evolution structure"
                                className="microled-image"
                                style={{ marginTop: '0.5rem', marginBottom: '1rem' }}
                            />

                            <p className="microled-info__desc">
                                MicroLED is a comparatively young display technology. It moved from a
                                university research finding, to a handful of large commercial demonstrations,
                                to today's push toward mainstream televisions, wearables, and Augmented Reality (AR) devices,
                                all within about two and a half decades.
                            </p>

                            <h3 className="microled-info__title">Origins</h3>
                            <p className="microled-info__desc">
                                MicroLED technology traces back to 2000, when a research group at Texas Tech
                                University first demonstrated arrays of microscopic, individually addressable
                                LEDs. For over a decade the technology mostly stayed in research labs while
                                the mass-transfer and driving methods needed to make it practical were
                                worked out.
                            </p>

                            <h3 className="microled-info__title">First Commercial Demonstrations</h3>
                            <p className="microled-info__desc">
                                In 2012, Sony unveiled the first large commercial MicroLED display, a
                                55-inch "Crystal LED" panel built from millions of individually driven
                                red, green, and blue chips. The demonstration showed off the format's deep
                                blacks and wide color coverage, and set the direction other manufacturers
                                would follow. Samsung entered the space in 2018 with a 146-inch modular
                                MicroLED display called "The Wall," shown at CES, which pushed the
                                technology toward tiled, large-format installations.
                            </p>
                            <div style={{ textAlign: 'center', width: '100%' }}>
                                <div className="square-img-frame app-img-frame">
                                    <img 
                                        src="https://www.sony.com/en/SonyInfo/News/Press/201201/ik0fha000000g304-img/8ido1800000ep99s.jpg" 
                                        alt="Sony TV" 
                                        className="microled-add-img"
                                    />
                                </div>
                                <p className="microled-img-caption">
                                    <strong>Sony 55-inch "Crystal LED" panel</strong>
                                </p>
                            </div>

                            <h3 className="microled-info__title">Current State</h3>
                            <p className="microled-info__desc">
                                Today, MicroLED is emerging in premium televisions, wearables, and AR
                                devices, with manufacturers continuing to refine the mass-transfer processes
                                needed to place millions of microscopic chips accurately and affordably.
                                High tooling costs and a limited number of qualified suppliers still keep
                                MicroLED mostly in the premium and large-format tiers, but the underlying
                                technology continues to mature year over year.
                            </p>
                            <div style={{ textAlign: 'center', width: '100%' }}>
                                <div className="square-img-frame app-img-frame">
                                    <img 
                                        src="https://www.auo.com/upload/media/media/News_Archive/20250512_3.jpg" 
                                        alt="AR Glasses" 
                                        className="microled-add-img"
                                    />
                                </div>
                                <p className="microled-img-caption">
                                    <strong>AUO AR smart glasses</strong>
                                </p>
                            </div>
                        </>
                    )}

                    {activeTab === 'tech' && (
                        <>
                            <h2 className="microled-info__title">Introduction and Fundamentals</h2>
                            <p className="microled-info__desc">
                                MicroLED (also known as mLED or µLED) is a display technology built from
                                tiny, self-emitting LED devices that directly create each color pixel,
                                producing bright, energy-efficient, and high-contrast images. Because the
                                LEDs themselves emit light and can be individually controlled, MicroLED is
                                structurally simpler than an LCD, which relies on a separate backlight and
                                color filters. This gives MicroLED better contrast and response time along
                                with high efficiency, and, unlike LCD, allows displays to be made flexible.
                                Its main drawbacks are manufacturing complexity and cost, which currently
                                limit it to premium televisions, wearables, and AR devices.
                            </p>

                            <h3 className="microled-info__title">Who developed MicroLED?</h3>
                            <p className="microled-info__desc" style={{ marginTop: '0.5rem' }}>
                                MicroLED technology was invented in 2000 by a husband-and-wife research
                                team, Prof. Hongxing Jiang and Prof. Jingyu Lin, while they were
                                professors at Kansas State University. Their group first demonstrated
                                electrically driven, individually addressable microscopic LED arrays,
                                laying the groundwork for the microdisplay technology. In 2008 the pair
                                relocated their research group to Texas Tech University, where in 2009
                                they and their colleagues realized the first active-driving,
                                high-resolution MicroLED microdisplay by integrating a MicroLED array
                                with a CMOS driver chip. Jiang and Lin continue to lead MicroLED research
                                today as co-directors of the Center for Nanophotonics at Texas Tech.
                            </p>
                            <div style={{ display: 'flex', width: '100%', gap: '2.5rem', justifyContent: 'center', flexWrap: 'wrap', marginTop: '1.5rem' }}>
                                <div style={{ textAlign: 'center' }}>
                                   <img
                                        src={jiangImg.src}
                                        alt="Prof. Hongxing Jiang"
                                        style={{
                                            width: '150px',
                                            height: '200px',
                                            objectFit: 'cover',
                                            borderRadius: '50% / 40%',
                                            border: '4px solid #3b82c4',
                                            display: 'block',
                                            margin: '0 auto'
                                        }}
                                    />
                                    <p className="microled-info__desc" style={{ marginTop: '0.75rem', fontSize: '0.9rem', lineHeight: '1.4' }}>
                                        Prof. Hongxing Jiang<br />
                                        Co-inventor of MicroLED (2000)
                                    </p>
                                </div>
                                <div style={{ textAlign: 'center' }}>
                                    <img
                                        src={linImg.src}
                                        alt="Prof. Jingyu Lin"
                                        style={{
                                            width: '150px',
                                            height: '200px',
                                            objectFit: 'cover',
                                            borderRadius: '50% / 40%',
                                            border: '4px solid #3b82c4',
                                            display: 'block',
                                            margin: '0 auto'
                                        }}
                                    />
                                    <p className="microled-info__desc" style={{ marginTop: '0.75rem', fontSize: '0.9rem', lineHeight: '1.4' }}>
                                        Prof. Jingyu Lin<br />
                                        Co-inventor of MicroLED (2000)
                                    </p>
                                </div>
                            </div>

                           
                            {/* Close-up visual of MicroLED chips */}
                            <h3 className="microled-info__title">Close-up View of MicroLED Chips</h3>
                            <div style={{ margin: '0rem 0' }}>

                                <div className="microled-cells">
                                    <div className="cell red"></div>
                                    <div className="cell green"></div>
                                    <div className="cell blue"></div>
                                </div>

                                <p className="microled-info__desc" style={{ marginTop: '1rem', textAlign: 'center' }}>
                                    Each pixel is built from one red, one green, and one blue chip, each
                                    independently driven and combined to form a full-color image.
                                </p>
                            </div>
                        </>
                    )}

                    {activeTab === 'apps' && (
                        <>
                            <h2 className="microled-info__title">Applications</h2>
                            <p className="microled-info__desc">
                                MicroLED is emerging wherever brightness, contrast, and long-term reliability
                                matter most. Documented and demonstrated uses include: premium and
                                large-format televisions, tiled commercial display walls, wearables, and
                                AR devices, alongside research pushing MicroLED toward flexible and
                                near-eye displays.
                            </p>
                            <div style={{ textAlign: 'center', width: '100%' }}>
                                <div className="square-img-frame app-img-frame">
                                    <img 
                                        src="https://images.fonearena.com/blog/wp-content/uploads/2019/12/Samsung-The-Wall.gif" 
                                        alt="Samsung TV" 
                                        className="microled-add-img"
                                    />
                                </div>
                                <p className="microled-img-caption">
                                    <strong>Samsung "The Wall"</strong>
                                </p>
                            </div>
                        </>
                    )}

                    {activeTab === 'perf' && (
                        <>
                            <h3 className="microled-info__title">Advantages</h3>
                            <div className="microled-adv-lim">
                                <ul className="microled-info__desc">
                                    <li>Brighter output with colors that read as more accurate and true to life</li>
                                    <li>Deep, true blacks and strong contrast without needing a separate backlight</li>
                                    <li>Thinner, lighter, and more power-efficient thanks to the self-illuminating design</li>
                                    <li>Extremely fast response times, well suited to gaming and fast video</li>
                                    <li>Long lifespan with no burn-in and strong tolerance to heat and humidity</li>
                                    <li>Can be built on curved or flexible backplanes for varied screen shapes</li>
                                </ul>
                            </div>

                            <h3 className="microled-info__title">Limitations</h3>
                            <div className="microled-adv-lim">
                                <ul className="microled-info__desc">
                                    <li>Specialized tools and dedicated fabrication facilities make production costly</li>
                                    <li>Only a small number of suppliers can currently provide the required materials</li>
                                    <li>Mass transfer technology for placing millions of microscopic LEDs is still maturing</li>
                                    <li>High manufacturing complexity narrows which companies can enter the market</li>
                                </ul>
                            </div>
                        </>
                    )}

                    {activeTab === 'quiz' && (
                        <div style={{ maxWidth: '700px', margin: '0 auto', width: '100%' }}>
                            <h2 className="microled-info__title">🧠 MicroLED Quiz Challenge</h2>
                            <p className="microled-info__desc">
                                Test what you've learned about MicroLED display technology! Answer all
                                5 questions to get your score.
                                <br /><br />
                                🔊 Turn your volume up for the full experience!
                            </p>

                            {!quizComplete && quizQuestions.length > 0 ? (
                                <div style={{ marginTop: '2rem' }}>

                                    <div style={{ marginBottom: '1rem', fontSize: '0.9rem', color: '#666' }}>
                                        Question {currentQuestion + 1} of {quizQuestions.length}
                                    </div>

                                    <h3 className="microled-info__title" style={{ marginBottom: '1.5rem' }}>
                                        {quizQuestions[currentQuestion].question}
                                    </h3>

                                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                                        {quizQuestions[currentQuestion].options.map((option, index) => (
                                            <button
                                                key={index}
                                                onClick={() => handleAnswer(index)}
                                                disabled={selectedAnswer !== null}
                                                style={{
                                                    padding: '0.85rem 1.25rem',
                                                    textAlign: 'left',
                                                    borderRadius: '8px',
                                                    border: '2px solid #ddd',
                                                    background: selectedAnswer === null
                                                        ? 'white'
                                                        : index === quizQuestions[currentQuestion].correct
                                                            ? '#d4edda'
                                                            : selectedAnswer === index
                                                                ? '#f8d7da'
                                                                : 'white',
                                                    borderColor: selectedAnswer === null
                                                        ? '#ddd'
                                                        : index === quizQuestions[currentQuestion].correct
                                                            ? '#28a745'
                                                            : selectedAnswer === index
                                                                ? '#dc3545'
                                                                : '#ddd',
                                                    cursor: selectedAnswer === null ? 'pointer' : 'default',
                                                    transition: 'all 0.2s ease'
                                                }}
                                            >
                                                {option}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            ) : quizComplete ? (
                                <div style={{ textAlign: 'center', marginTop: '2rem', padding: '2.5rem', borderRadius: '12px', background: 'rgba(15, 110, 86, 0.08)', position: 'relative', overflow: 'hidden', border: '3px solid #0f6e56' }}>

                                    {score === quizQuestions.length && (
                                        <canvas
                                            ref={canvasRef}
                                            style={{
                                                position: 'absolute',
                                                top: 0,
                                                left: 0,
                                                width: '100%',
                                                height: '100%',
                                                pointerEvents: 'none'
                                            }}
                                        />
                                    )}

                                    <h3 className="microled-info__title" style={{ animation: 'bounceIn 0.6s ease-out', fontSize: '2.2rem', fontWeight: '900', position: 'relative', zIndex: 2 }}>🎉 QUIZ COMPLETE! 🎉</h3>

                                    <p style={{
                                        fontSize: '4rem',
                                        fontWeight: '900',
                                        margin: '1.5rem 0',
                                        color: '#0f6e56',
                                        animation: 'bounceIn 0.8s ease-out 0.2s both',
                                        letterSpacing: '2px',
                                        textShadow: '0 4px 12px rgba(15, 110, 86, 0.3)',
                                        position: 'relative',
                                        zIndex: 2
                                    }}>
                                        {score} / {quizQuestions.length}
                                    </p>

                                    <p className="microled-info__desc" style={{
                                        fontSize: '1.4rem',
                                        fontWeight: '700',
                                        animation: 'fadeUp 0.8s ease-out 0.4s both',
                                        lineHeight: '1.6',
                                        position: 'relative',
                                        zIndex: 2
                                    }}>
                                        {score === 5 ? "🌟 PERFECT SCORE! YOU'RE A MICROLED EXPERT!"
                                            : score >= 3 ? "✨ AWESOME JOB! YOU KNOW YOUR MICROLED STUFF!"
                                                : "💥 NICE TRY! EXPLORE THE TABS AGAIN AND CHALLENGE YOURSELF ONCE MORE!"}
                                    </p>

                                    <button
                                        onClick={resetQuiz}
                                        className="btn"
                                        style={{ marginTop: '2rem', fontSize: '1.1rem', padding: '0.8rem 2rem', animation: 'fadeUp 0.8s ease-out 0.6s both', position: 'relative', zIndex: 2 }}
                                    >
                                        TRY AGAIN
                                    </button>
                                </div>
                            ) : (
                                <p className="microled-info__desc" style={{ textAlign: 'center', marginTop: '2rem' }}>Loading quiz...</p>
                            )}
                        </div>
                    )}

                    {activeTab === 'refs' && (
                        <>
                            <h2 className="microled-info__title">References</h2>
                            <ul className="microled-info__desc" style={{ lineHeight: '1.7', paddingLeft: '1.5rem' }}>
                                <li>
                                    Absen. (2023). <em>Analysis of Micro LED large screen display technology Chip and encapsulation structure</em>.
                                    <a href="https://www.absen.com/analysis-of-micro-led-large-screen-display-technology-chip-and-encapsulation-structure" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    CMG Visuals. (n.d.). <em>What is a microLED display and why it's superior to OLED</em>.
                                    <a href="https://www.cmgvisuals.com/led-screen-blog/what-is-a-microled-display-and-why-its-superior-to-oled" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    Delmic. (n.d.). <em>MicroLED: the next revolution in display technology</em>.
                                    <a href="https://blog.delmic.com/microled-revolutionary-technology" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    FlatpanelsHD. (2016, October 21). <em>An introduction to MicroLED; a new self-emitting display technology</em>.
                                    <a href="https://www.flatpanelshd.com/focus.php?subaction=showfull&id=1477048275" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    GreyB. (2025, February 7). <em>Micro-LED precision fabrication</em>.
                                    <a href="https://xray.greyb.com/micro-leds/micro-led-display-fabrication" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    HandWiki. (2025). <em>Engineering: MicroLED</em>.
                                    <a href="https://handwiki.org/wiki/Engineering:MicroLED" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    Kim, T. S., Ryu, J., Park, J., Liu, R., Choi, J., Kim, J., Hong, Y. J., Kim, D., & Shin, J. (2025). <em>Future trends of display technology: micro-LEDs toward transparent, free-form, and near-eye displays</em>. Light Science & Applications, 14(1), 335.
                                </li>
                                <li>
                                    MicroLED Association. (2025). <em>MicroLED microdisplays soft-standard</em> (Edition 2.0).
                                    <a href="https://www.microledassociation.com/wp-content/uploads/2025/02/MIA-MicroLED-standardization-microdisplays-2025-02.pdf" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    MicroLED-Info. (n.d.). <em>What is MicroLED</em>.
                                    <a href="https://www.microled-info.com/introduction" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    minimicroled.com. (2025, February 14). <em>The History and Development of Micro LED Technology</em>.
                                    <a href="https://www.minimicroled.com/the-history-development-micro-led-technology/" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    PatSnap Eureka. (2025, October 24). <em>What Are OLED vs MicroLED's Key Technical Challenges</em>.
                                    <a href="https://eureka.patsnap.com/report-oled-vs-microled-key-technical-challenges" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    PTCLed. (2025, January 22). <em>MicroLED VS OLED VS Mini LED: Which Display is the Future</em>.
                                    <a href="https://www.ptcled.com/academy/microled-vs-oled-vs-miniled.html" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    RF Wireless World. (n.d.). <em>What is Micro LED: Advantages and Disadvantages</em>.
                                    <a href="https://www.rfwireless-world.com/terminology/micro-led-advantages-disadvantages" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                                <li>
                                    TechRadar. (2025). <em>QLED vs OLED vs micro-LED: Which is the best TV tech in 2025?</em>.
                                    <a href="https://www.techradar.com/televisions/qled-vs-oled-vs-micro-led-which-is-the-best-tv-tech-in-2025" target="_blank" rel="noopener noreferrer" style={{ color: '#5076a7', textDecoration: 'underline' }}>
                                        Link to Article
                                    </a>
                                </li>
                            </ul>
                        </>
                    )}
                </div>
            )}
        </div>
    );
}
